version: '3'
services:
  users:
    build: ./users
    ports:
     - "8000:8000"
    depends_on:
     - mongo
    environment:
     - MONGO_URL=mongo
     - HOST=0.0.0.0
     - PORT=8000
     - MIN_USERNAME=3
     - MAX_USERNAME=16
     - MIN_PASSWORD=8
     - MAX_PASSWORD=16
  offers:
    build: ./offers
    ports:
    - "8001:8001"
    depends_on:
    - mongo
    environment:
    - MONGO_URL=mongo
    - HOST=0.0.0.0
    - PORT=8001
    - MIN_TITLE=10
    - MAX_TITLE=30
    - MIN_TEXT=20
    - MAX_TEXT=100
  mongo:
    image: "mongo:3.6.3"
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: